### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by Baroshem** [Morgbn/nuxt-csurf#1]
Hey Man,

Great work on this module. I have been planning to develop similar functionality for my https://github.com/Baroshem/nuxt-security but I just discovered that you have created one. 

Would you be interested in contributing into my module (that will soon probably become an oficiall nuxt module) with your functionality so that we can serve CSRF protection as a part of the general security module for Nuxt? :)

Let me know and I will do my best to help.

**Comment by Morgbn** [comment]
Hey @Baroshem 
Thanks, yes it could be interesting to include it in a bigger module
I will continue to fix the first bugs here, and then I will try to create a PR for nuxt-security :)

**Comment by Baroshem** [comment]
Awesome,

If you need my help at any point, please let me know. 

Also, contributing to my module does not mean that I will steal your work or anything. I will make sure to include you everywhere where the CSRF functionality will be displayed so that you could get more traction as you did a great work with this module. It's just that by having this functionality as a part of a bigger (more general) module, it is easier to get more users on board.

I have created an issue in my module for keeping track of this feature (as it was requested few times already). I will create a proposal for interface for options and how it could work based on your module :)

https://github.com/Baroshem/nuxt-security/issues/85
