### ISSUE TITLE
Supporting Web Crypto API (serverless environments)

### ISSUE THREAD

**Issue by zsilbi** [Morgbn/nuxt-csurf#11]
Hi!

This module is currently not usable in serverless environments. (eg Cloudflare Workers).
See: https://developers.cloudflare.com/workers/runtime-apis/web-crypto/

I made an experimental fork that uses the Web Crypto API , you can find it here: https://github.com/zsilbi/nuxt-csurf (requires Node.js 19+)

I don't know if a single package could supports both older Node versions and serverless enviroments with this new API, because of the missing imports,.

Best regards,
zsilbi

**Comment by 69u** [comment]
Hey there @zsilbi,

Thank you for creating this fork for serverless environments. I have been trying to install your fork but am finding it extremely difficult due to it not being a published package - if someone is able to assist me that would be greatly appreciated :)

[This is my fork that I have been playing around with](https://github.com/69u/nuxt-csurf)

Cheers,
69u

**Comment by Morgbn** [comment]
Hey!
I think it’s possible to have support for both, perhaps via the configuration (serverless: Boolean)
Don’t hesitate to push a PR, I’m very busy at now, but I will take a look, thanks

**Comment by zsilbi** [comment]
> Hey there @zsilbi,
> 
> Thank you for creating this fork for serverless environments. I have been trying to install your fork but am finding it extremely difficult due to it not being a published package - if someone is able to assist me that would be greatly appreciated :)
> 
> [This is my fork that I have been playing around with](https://github.com/69u/nuxt-csurf)
> 
> Cheers, 69u

Maybe the easiest way to test it is to create an archive and add to your project using pnpm peer dependencies.

package.json
```
"resolutions": {
    "nuxt-csurf": "./forked-nuxt-csurf.tar.gz",
}
```

> Hey! I think it’s possible to have support for both, perhaps via the configuration (serverless: Boolean) Don’t hesitate to push a PR, I’m very busy at now, but I will take a look, thanks

I don't think this is possible whitin the same package because the serverless runtimes will fail if the code contains any import from `crypto`.

**Comment by 69u** [comment]
> > Hey there @zsilbi,
> > Thank you for creating this fork for serverless environments. I have been trying to install your fork but am finding it extremely difficult due to it not being a published package - if someone is able to assist me that would be greatly appreciated :)
> > [This is my fork that I have been playing around with](https://github.com/69u/nuxt-csurf)
> > Cheers, 69u
> 
> Maybe the easiest way to test it is to create an archive and add to your project using pnpm peer dependencies.
> 
> package.json
> 
> ```
> "resolutions": {
>     "nuxt-csurf": "./forked-nuxt-csurf.tar.gz",
> }
> ```
> 
> > Hey! I think it’s possible to have support for both, perhaps via the configuration (serverless: Boolean) Don’t hesitate to push a PR, I’m very busy at now, but I will take a look, thanks
> 
> I don't think this is possible whitin the same package because the serverless runtimes will fail if the code contains any import from `crypto`.

with Cloudflare Workers the import is simply overwritten by [Web Crypto API](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/) so by adding the import to the code it extends compatibility to >19.0.0 users as well as my serverless environment - Is this not the case with other serverless environment providers?

**Comment by Morgbn** [comment]
Hey @zsilbi & @69u, I've just released a beta version that uses conditional exports to support multiple runtimes. Can you take a look at it ? (`npm i nuxt-csurf@beta`)

& Thanks to you @zsilbi, my code was much inspired by [your fork](https://github.com/zsilbi/nuxt-csurf)

_(Related issue: https://github.com/Baroshem/nuxt-security/issues/150)_

**Comment by Baroshem** [comment]
@Morgbn @zsilbi any news here?

I would like to merge it to solve the issues for the module users :)

**Comment by Morgbn** [comment]
I haven't yet had the time to test `nuxt-csurf@beta` on [other providers](https://nuxt.com/docs/getting-started/deployment#supported-hosting-providers) than Node hosting (like Cloudflare).
@69u or @zsilbi have you tested this beta ?
