### ISSUE TITLE
Type issue

### ISSUE THREAD

**Issue by rcerljenko** [Morgbn/nuxt-csurf#13]
Hi there,

Since version 1.3 you can't select a TS genereic return type like so:
```ts
useCsrfFetch<ApiExampleType>('...')
```

**Comment by Morgbn** [comment]
Hi @rcerljenko,
thanks for the information,
I've rewritten the function using the same types as [useFetch](https://github.com/nuxt/nuxt/blob/7046930a677f4c987afaee5a0165841b0e0a517f/packages/nuxt/src/app/composables/fetch.ts), I hope this solves your problem !

**Comment by rcerljenko** [comment]
Hi @Morgbn ,

Yes it did solve it. Thanks for the fast fix!  :)

**Comment by rsoltanzadeh** [comment]
Not working for me on 1.5.1. Using `useCsrfFetch` instead of `useFetch` changes the correct type to `any`.

**Comment by rsoltanzadeh** [comment]
Doesn't work with 1.6.1 either.
