### ISSUE TITLE
encryptAlgorithm, aes-256-cbc by default node, AES-CBC serverless

### ISSUE THREAD

**Issue by imcm7** [Morgbn/nuxt-csurf#15]
In docs `encryptAlgorithm, aes-256-cbc by default node, AES-CBC serverless`.
But type check warn `Type '"aes-256-cbc"' is not assignable to type '"AES-CBC"'.`

**Comment by johngerome** [comment]
I'm also having the same problem. Any workaround on this ?

**Comment by Morgbn** [comment]
It seems that by default, typescript takes the web/serverless environment and not node. I don't know how to change that.
But for information, if encryptAlgorithm is not set, the correct value will be set automatically depending on the runtime environment
