### ISSUE TITLE
'$csrfFetch' is of type 'unknown'.

### ISSUE THREAD

**Issue by timstrasser** [Morgbn/nuxt-csurf#19]
When using `const { $csrfFetch } = useNuxtApp();` in a Pinia store, the return type of $csrfFetch is unknown. Is this a known issue or do I import $csrfFetch wrong?

**Comment by Morgbn** [comment]
Maybe related to: https://github.com/vuejs/pinia/discussions/1513 and https://github.com/vuejs/pinia/discussions/1513
In a Pinia store you can use useCsrfFetch() without any problem.
