### ISSUE TITLE
Ability to disable module

### ISSUE THREAD

**Issue by genu** [Morgbn/nuxt-csurf#25]
I think there should be a way to disable the module. For example, on local, development is faster with csrf disabled since a page refresh isn't necessary when rebuilding server.

For more context see also here:

https://github.com/Baroshem/nuxt-security/issues/334

Tagging @Baroshem for visibility

**Comment by Baroshem** [comment]
@Morgbn 

What are your thoughts on that?

**Comment by Morgbn** [comment]
Hello, I will try to add this feature in the next release ;)
