### ISSUE TITLE
403 CSRF Token Mismatch after some time

### ISSUE THREAD

**Issue by vjanoch** [Morgbn/nuxt-csurf#27]
We use `[nuxt-csurf](https://github.com/Morgbn/nuxt-csurf)` implicitly via [`nuxt-security`](https://github.com/Baroshem/nuxt-security).

After visiting the application the CSRF Tokens are valid and all forms (with server side validation or submissins) work as expected.

If we keep the window open or use only client side navigation, the CSRF Token verification fails (`403 CSRF Token Mismatch`) after a while (approximately 10-15 minutes, not exactly measured) although the cookie `__Host-csrf ` and the header `Csrf-Token` are still send with the corresponding requests.

If the page is reloaded the requests work for another certain time again. The cookie remains the same, but the `Csrf-Token` gets updated.

**Comment by nandita121189** [comment]
Any update on the above? I'm also getting a similar issue.

**Comment by Morgbn** [comment]
Hello, does this happen in production ? or just in dev mode ?

**Comment by nandita121189** [comment]
This doesn't happen in the dev mode. It happens in the Production mode and that too intermitently. Like the first call gets passed but the 2nd fails. Sometimes the second call passes even though the first had failed.

**Comment by sathishzakapps** [comment]
Do you run your nuxt in multiple instances and without Session Affinity? if so I think we have a problem with this module!!!

**Comment by sathishzakapps** [comment]
@Morgbn We are facing the same kind of issue where we are running nuxt instances in different machine and we get into the same issue. Do you have any work around/implementation for this?

**Comment by Morgbn** [comment]
In the case of multiple instances behind a load balancer, sticky-session may need to be activated (you can find more information and how to enable sticky session [here](https://socket.io/docs/v4/using-multiple-nodes))
