### ISSUE TITLE
403 CSRF Token Mismatch Error with `nuxt-csurf` in Nuxt 3 Application

### ISSUE THREAD

**Issue by nicokempe** [Morgbn/nuxt-csurf#28]
### Description

I'm encountering a `403 CSRF Token Mismatch` error in my Nuxt 3 application when attempting to submit a form using the `nuxt-csurf` module for CSRF protection. Despite correctly including the CSRF token in the request headers, the server responds with a token mismatch error.

### Steps to Reproduce

1. Configured `nuxt-csurf` in `nuxt.config.ts` according to the documentation.
2. Initially tried using `useCsrfFetch` for CSRF token handling, then switched to manual inclusion using `$fetch` due to component mounting issues.
3. Despite these efforts, the server consistently returns a `403 CSRF Token Mismatch` error upon form submission.

### Expected Behavior

The form submission should be processed without any CSRF token mismatch errors, assuming the CSRF token provided by the client matches the server's expectations.

### Actual Behavior

The server responds with a `403 CSRF Token Mismatch` error, indicating a discrepancy between the provided and expected CSRF tokens.

### Environment

```plaintext
- Operating System: Windows_NT
- Node Version: v20.8.1
- Nuxt Version: 3.10.0
- CLI Version: 3.10.0
- Nitro Version: 2.8.1
- Package Manager: pnpm@8.14.1
- User Config: preset, experimental, devtools, modules, serverMiddleware, nitro, i18n, cloudflareAnalytics, turnstile, css, postcss, mongoose, app, runtimeConfig, routeRules, image, security, csurf, content, typescript
- Runtime Modules: @nuxt/image@1.3.0, @nuxt/devtools@1.0.8, @nuxt/content@2.11.0, @nuxtjs/i18n@8.0.1, @nuxtjs/turnstile@0.6.3, @nuxtjs/tailwindcss@6.11.3, nuxt-security@1.1.0, nuxt-headlessui@1.1.5, nuxt-cloudflare-analytics@1.0.8, nuxt-csurf@1.4.0
```

### Attempts to Resolve
* Checked client-side CSRF token retrieval and inclusion in request headers. (Even tried to include it manually)
* Reviewed server and client configurations for potential issues.

### Additional Context
I have closely followed the documentation for both Nuxt 3 and nuxt-csurf and ensured my setup aligns with the recommended practices. However, the issue persists, and I'm unable to identify the cause of the CSRF token mismatch error. Any guidance or insights would be greatly appreciated.

**Comment by priyachawla11** [comment]
We are getting the same issue for the following configuration:

```
- Node Version: 20.5.0
- Nuxt Version:  3.7.0
- Nitro Version: 2.8.1
- Package Manager: pnpm@8.14.1
```

Client-side CSRF token retrieved and included in request headers are same, still getting CSRF token mismatch error.

**Comment by Morgbn** [comment]
Hello, weird, I'm using the module in a similar environment but I don't get these errors, can you provide a link to a minimal reproduction? I'm very busy at the moment so I can't investigate further.

**Comment by nicokempe** [comment]
> Any update on the above? I'm also getting a similar issue.

For now I have just removed the module because I haven't got an answer. In the long run I do probably have to look for an own solution. I couldn't find a lot of Open Source projects nor resources in general. I will look for the problem again today and try to provide a minimal reproduction. Hopefully just a dumb mistake of myself

**Comment by nicokempe** [comment]
Cookie "csrf=ac6fd71b-8998-47c7-911a-.............." exists and is there but nothing is in the headers. There only "undefined" is given:
https://github.com/nicokempe/nuxt-csrf-test/tree/test/%24fetch

**Comment by zhaolinlau** [comment]
same problem here

**Comment by nicokempe** [comment]
Any idea @Morgbn?

**Comment by zhaolinlau** [comment]
i've tried with the nuxt-csrf in [nuxt security](https://nuxt-security.vercel.app/documentation/middleware/csrf) looks fine for me

**Comment by zhaolinlau** [comment]
> i've tried with the nuxt-csrf in [nuxt security](https://nuxt-security.vercel.app/documentation/middleware/csrf) looks fine for me

I take back my words, it happens sometimes.

**Comment by nicokempe** [comment]
any update @Morgbn

**Comment by Morgbn** [comment]
Hello @nicokempe, I tried to run your repo (https://github.com/nicokempe/nuxt-csrf-test)
It works for me, I just comment `encryptAlgorithm` from the configuration (you have to set 'AES-CBC' only in serveless context, it's usually better to let nuxt-csrf find the right algorithm according to context)
Can you test without  `encryptAlgorithm` set ?

**Comment by nicokempe** [comment]
Hello @Morgbn, thank you very much for your answer! I haven't gotten around to testing that yet, I've completely disabled CSRF for now, I'm deploying to Cloudflare Pages, hence the encryption set. But if the module finds out for itself which encryption has to be used, that's even better. I'll have a look, but if it worked for you, that sounds promising, thanks for taking a look! :)

**Comment by mwilliford** [comment]
Same issue here, I include const {csrf} = useCSRF() on my login page, in my <script lang='ts'> and csrf is always undefined.  So, I think this is why my protected POST is not getting any headers set with csrfFetch

**Comment by nicokempe** [comment]
> Same issue here, I include const {csrf} = useCSRF() on my login page, in my <script lang='ts'> and csrf is always undefined. So, I think this is why my protected POST is not getting any headers set with csrfFetch

I haven't gotten around to it yet, do you use a specific encryption in your Nuxt config?

**Comment by zhaolinlau** [comment]
@nicokempe any update?

**Comment by zhaolinlau** [comment]
@Morgbn any update?

**Comment by MikesGlitch** [comment]
I'm also experiencing this issue. My config is:

    csrf: {
      enabled: true,
      https: true, // https is true even on local
      addCsrfTokenToEventCtx: true,
    },

I can see the csrf headers being added to the request. 
![image](https://github.com/Morgbn/nuxt-csurf/assets/5285928/d199b2fe-822c-4330-b034-740464823a92)

It works intermittently but when I navigate pages, and try to use the csrf again I get 
![image](https://github.com/Morgbn/nuxt-csurf/assets/5285928/59974526-0424-4632-a37a-358f71b4f110)

with the same exact csrf:
![image](https://github.com/Morgbn/nuxt-csurf/assets/5285928/eede2f7f-80a0-4c39-8231-9673c499c82a)

**Comment by Stf-F** [comment]
Mine works most of the time. But...
I have noticed that if a form hasn't been submitted after a short while (a few minutes), the server will consistently return a 403, as if they the tokens (or the cookie?) had an expiry timestamp attached.
Now, I have had a quick look at the code of the package and also [uncsrf](https://github.com/Morgbn/uncsrf/tree/main) which nuxt/crsrf is built upon  but couldn't find anything that would actually do that.
There is therefore something else that causes the server and the client to get out of sync is some cases.

**Comment by Ribeiro-Tiago** [comment]
I just ran into this issue. Fixed it using the node encryptAlgorithm prop instead of the serverless like i had initially configured. My config looks like 
```
csurf: {
    https: process.env.NODE_ENV === "production", // default true if in production
    encryptAlgorithm: process.env.NODE_ENV === "local" ? "AES-CBC" : "aes-256-cbc", // by default 'aes-256-cbc' (node), 'AES-CBC' (serverless)
    addCsrfTokenToEventCtx: true, // default false, to run useCsrfFetch on server set it to true
},
```

**Comment by Morgbn** [comment]
I'm closing this error for lack of reproduction. Sorry guys many things in the environment can probably break the csrf cookie, without replication I can't debug anything.

**Comment by nicokempe** [comment]
> Hello @nicokempe, I tried to run your repo (https://github.com/nicokempe/nuxt-csrf-test) It works for me, I just comment `encryptAlgorithm` from the configuration (you have to set 'AES-CBC' only in serveless context, it's usually better to let nuxt-csrf find the right algorithm according to context) Can you test without `encryptAlgorithm` set ?
> 
> _excuse the late reply, last few weeks have been very busy for me_

There is a reproduction in which the same error occurs @Morgbn. Even after changing the encryption the error occurs @Morgbn. It does take some time but it definitely occurs after a while. Thats why so many people do have problems with this. Could you please re-open this issue? It is sadly still relevant. 😅

**Comment by Ribeiro-Tiago** [comment]
I end up removing this dependency because it always randomly failing 

As far as I could tell, any sort of state change would make this fail. E.g.: hot reloading (i guess hot reloading would trigger a token refresh on client side so they wouldn't match anymore?), some time of inactivity

**Comment by bojanrajh** [comment]
@Morgbn Unfortunatelly, we are experiencing the same issue.

So far, I've tracked the issue down to this error being silently suppressed by `uncsrf`: https://github.com/Morgbn/uncsrf/blob/main/src/csrf.node.ts#L72

```
error:1C800064:Provider routines::bad decrypt

  at Decipheriv.final (node:internal/crypto/cipher:193:29)
  at Module.verify (node_modules/.pnpm/uncsrf@1.1.1_patch_hash=mexgzciky4rudhcyhw7j326cm4/node_modules/uncsrf/dist/csrf.node.mjs:46:73)
  at Object.handler (node_modules/.pnpm/nuxt-csurf@1.5.2_patch_hash=tmjxkeopg6lwrvsgw2x3h6cwlq_rollup@4.18.0/node_modules/nuxt-csurf/dist/runtime/server/middleware/csrf.mjs:26:35)
```

All 4 parameters passed to `csrf.verify(secret, token, encryptSecret, encryptToken)` seems okay, with the same length on production (Vercel serverless functions) and locally.

Switching from `aes-256-cbc` to `AES-CBC` results in the `csrf-token` being `undefined` in meta tag already.

It has nothing to do with `encryptSecret` containing special chars (`+`, `/`).

Activating/Deactivating `autopadding` on `decipher` doesn't help.

Working example (`uncsrf.verify`):
```
secret = '56ed3274-5233-4d25-bfbc-2af656f0838e'
token = 'f36kJCBE1zN1N3Sk8aHIkg==:BtCwdcE/rWBdLcsTDqHI6RMnAU7yFzDIL5iLPew2H2cIj0mJm7ikQI6Mdtt4Lv6v'
encryptSecret = 'Wf9FnEYqZmR4JWV1x06w15fdzDb50g=='
encryptAlgorithm = 'aes-256-cbc'
```

Broken example:
```
secret = 'b6c3f003-c6cd-427c-ade2-407de920c1f9'
token = 'r+a+957fZGDURiJQDZLeZw==:jCzyvuNdC4Jd1Q/C4/u7wRSnqyO2vhRk9Y38EsV3fjs3wf/AcGNk1IxLfWv0hylx'
encryptSecret = '2G+RCCN2/biURc+Xin/1Y9KlfBtBeA=='
encryptAlgorithm = 'aes-256-cbc'
```

Broken example 2:
```
secret = '1297d34c-64b6-44ef-86d3-f646d7318055'
token = 'R1Bv7NgyP18U3Clh3zsmsQ==:RRCBi5AeRQmktayDoz1s6fnpoRJA3HvL+7MQxXM0hAWkZnSAlQKpGZK1aINaI4Da'
encryptSecret = 'eY7gQ5R3x+dmdunBjnKrrO2xAzAAiw=='
encryptAlgorithm = 'aes-256-cbc'
```

Any help and other info is appreciated!

**Comment by OTTIN-T** [comment]
> @Morgbn Unfortunatelly, we are experiencing the same issue.
> 
> So far, I've tracked the issue down to this error being silently suppressed by `uncsrf`: https://github.com/Morgbn/uncsrf/blob/main/src/csrf.node.ts#L72
> 
> ```
> error:1C800064:Provider routines::bad decrypt
> 
>   at Decipheriv.final (node:internal/crypto/cipher:193:29)
>   at Module.verify (node_modules/.pnpm/uncsrf@1.1.1_patch_hash=mexgzciky4rudhcyhw7j326cm4/node_modules/uncsrf/dist/csrf.node.mjs:46:73)
>   at Object.handler (node_modules/.pnpm/nuxt-csurf@1.5.2_patch_hash=tmjxkeopg6lwrvsgw2x3h6cwlq_rollup@4.18.0/node_modules/nuxt-csurf/dist/runtime/server/middleware/csrf.mjs:26:35)
> ```
> 
> All 4 parameters passed to `csrf.verify(secret, token, encryptSecret, encryptToken)` seems okay, with the same length on production (Vercel serverless functions) and locally.
> 
> Switching from `aes-256-cbc` to `AES-CBC` results in the `csrf-token` being `undefined` in meta tag already.
> 
> It has nothing to do with `encryptSecret` containing special chars (`+`, `/`).
> 
> Activating/Deactivating `autopadding` on `decipher` doesn't help.
> 
> Working example (`uncsrf.verify`):
> 
> ```
> secret = '56ed3274-5233-4d25-bfbc-2af656f0838e'
> token = 'f36kJCBE1zN1N3Sk8aHIkg==:BtCwdcE/rWBdLcsTDqHI6RMnAU7yFzDIL5iLPew2H2cIj0mJm7ikQI6Mdtt4Lv6v'
> encryptSecret = 'Wf9FnEYqZmR4JWV1x06w15fdzDb50g=='
> encryptAlgorithm = 'aes-256-cbc'
> ```
> 
> Broken example:
> 
> ```
> secret = 'b6c3f003-c6cd-427c-ade2-407de920c1f9'
> token = 'r+a+957fZGDURiJQDZLeZw==:jCzyvuNdC4Jd1Q/C4/u7wRSnqyO2vhRk9Y38EsV3fjs3wf/AcGNk1IxLfWv0hylx'
> encryptSecret = '2G+RCCN2/biURc+Xin/1Y9KlfBtBeA=='
> encryptAlgorithm = 'aes-256-cbc'
> ```
> 
> Broken example 2:
> 
> ```
> secret = '1297d34c-64b6-44ef-86d3-f646d7318055'
> token = 'R1Bv7NgyP18U3Clh3zsmsQ==:RRCBi5AeRQmktayDoz1s6fnpoRJA3HvL+7MQxXM0hAWkZnSAlQKpGZK1aINaI4Da'
> encryptSecret = 'eY7gQ5R3x+dmdunBjnKrrO2xAzAAiw=='
> encryptAlgorithm = 'aes-256-cbc'
> ```
> 
> Any help and other info is appreciated!
> 
> Update: forms that do work, stop working on hot reload of the server, same as @Ribeiro-Tiago . But this is not such an issue if production would work as expected. :)
> 
> Update 2: locally, `csrf-token` meta tag gets updated on every refresh on every page. On production (staging), the token on homepage (/) didn't refresh even after logging in and logging out, but token on other pages gets refreshed on every refresh. We are using Nuxt 3 with client-side rendering and vercel preset.
> 
> **Update 3: the token is the same using 2 different browsers in incognito mode! Even by 2 different users in 2 different countries. It's pre-rendered?**
> 
> **Update 4: it's obvious. CSRF token is statically pre-rendered and not updated when client-side is active (at least).**
> 
> Solution: disable prerendering on the pages where CSRF is needed: https://nuxt.com/docs/guide/concepts/rendering#deploying-a-static-client-rendered-app
> 
> ```
>   ssr: false,
>   csurf: {
>     enabled: true,
>     https: process.env.NODE_ENV === 'production',
>     cookie: {
>       path: '/',
>       httpOnly: true,
>       sameSite: 'strict',
>       secure: process.env.NODE_ENV === 'production'
>     },
>     methodsToProtect: ['POST', 'PUT', 'PATCH', 'DELETE'],
>     encryptSecret: process.env.CSURF_ENCRYPT_SECRET || '',
>   },
> ```
> 
> Update 5: solution with `routes.clear()` breaks Nuxt Content, a workaround is to use `routes.delete('/')` instead.
> 
> Also see: #40

Having done the same research, I have come to the same conclusion. The token isn't being refreshed correctly between the server and the client. How to solve the problem is totally beyond my skills...
I've just tried your solution of using the ‘prerender:routes’ hooks. It works very well but I'm not quite sure what impact it has on my application. I no longer benefit from server-side pre-rendering? So the benefits of SSR aren't there?
