### ISSUE TITLE
TS support

### ISSUE THREAD

**Issue by rcerljenko** [Morgbn/nuxt-csurf#3]
Nuxt TSC complains when you try to overrride a return type of `useCsrfFetch` function like this:
```php
const response = await useCsrfFetch<TurnstileValidationResponse>('/_turnstile/validate', {
    method: 'POST',
    body: {
        token
    }
})
```

Normal `useFetch` allows that, Could you probably type this function just like normal `useFetch` ?

**Comment by Morgbn** [comment]
Hi!
Hope this commit will fix this bug

**Comment by rcerljenko** [comment]
thanks!
