### ISSUE TITLE
Support nuxt prerendering

### ISSUE THREAD

**Issue by AlexXanderGrib** [Morgbn/nuxt-csurf#40]
Prerendering is great for optimizing the Largest Contentful Paint (LCP). However, it currently breaks because the CSRF token is static and does not update per user.

For example, the CSRF token is the same for every user:
```html
<meta name="csrf-token" content="mnlY+K07bUag3cRk50HHzQ==:8bQGfpaFUxEghvQVeaJd3/z+F0BBFtFradiuDdNaZxAMCZiVRZrqcMOvmKsO0sPy">
```

It would be ideal if the plugin handled CSRF tokens dynamically as follows:
1. If prerendering is detected, add `<meta name="csrf-token" content="%CSRF_TOKEN%">` to the HTML head.
2. On each request, replace `%CSRF_TOKEN%` with the actual token.

Security considerations:
- Users could potentially post a comment with `%CSRF_TOKEN%`, which would then be replaced by the actual token.
  - As a safeguard, replace only the first occurrence of `%CSRF_TOKEN%` to ensure users cannot edit the `<head>` section of the document.

**Comment by Morgbn** [comment]
Hello @AlexXanderGrib
can you please share your `nuxt.config` ? Do you use `nitro.static = true` ?
I have tested with `nitro.rerender: { routes: ['/'] }` I don't get any errors.

**Comment by AlexXanderGrib** [comment]
I used something like this, can you please share a proper setup?

```
  routeRules: {
    '*': { prerender: true },
   } 
 ```

**Comment by Morgbn** [comment]
I think prerender API routes it’s not a good idea.
Try to add: `'/api/**': { prerender: false }` 😉
