### ISSUE TITLE
Doesn't work on serverless

### ISSUE THREAD

**Issue by moshetanzer** [Morgbn/nuxt-csurf#41]
Hi,

As explained here at length this module does NOT work on serverless since state is not saved and if server isn't warm/hot, cold restarts happen all the time which requires page reloads (on user side to update token) basically any time you use a form that has CSRF protection. 

This is discussed at length in the nuxt security package https://github.com/Baroshem/nuxt-security/issues/477

Unless this issue is sorted or a different method is used, using this will create a really bad ux in your project. Author is aware of this but has not responded to queries.

**Comment by Morgbn** [comment]
Hi,
can you please share your nuxt.config ?
I've hosted [the playground on cloudfare](https://nuxt-csurf.pages.dev/), it seems to work

**Comment by bojanrajh** [comment]
We've been debuggin similar issue with Vercel last month, here are our findings: https://github.com/Morgbn/nuxt-csurf/issues/28#issuecomment-2194360017

**Comment by moshetanzer** [comment]
Yip. Not sure why maintainer doesn’t seem to see issue. There are issues open also in the nuxt security package. See the origin solution I posted in Nuxt Security it works well and basically is supported by every browser and is suggested by owasp 

https://github.com/Baroshem/nuxt-security/issues/477

**Comment by moshetanzer** [comment]
Hey @Morgbn the playground is the repro. Just deploy on Vercel. Not exactly sure how cloudflare infra works.

**Comment by ccwebgroup** [comment]
Playground, with CSRF header, not working. check it out.

**Comment by Barbapapazes** [comment]
Refresh the page and then retry, it works but indeed, the cookie with the csrf token is not set at the first request.

**Comment by Barbapapazes** [comment]
@Morgbn to reproduce, you can clear the site data from the online playground page, refresh and try the `POST /test (with csrf token)`.

**Comment by Barbapapazes** [comment]
This could come from the `encryptSecret` that change from one request to another?

**Comment by Barbapapazes** [comment]
I deploy the playground on my Cloudflare account to check and the key change between two requests. The logs above are the result of the following `console.log`

```ts
import * as csrf from "uncsrf";
import { defineEventHandler, getCookie, getHeader, createError } from "h3";
import { useRuntimeConfig, getRouteRules } from "#imports";
import { useSecretKey } from "../helpers";
import { defuReplaceArray } from "../../utils";

const baseConfig = useRuntimeConfig().csurf;

export default defineEventHandler(async (event) => {
  const { csurf } = getRouteRules(event);
  if (csurf === false || csurf?.enabled === false) {
    return;
  } // csrf protection disabled for this route

  const csrfConfig = defuReplaceArray(csurf ?? {}, baseConfig);
  const method = event.node.req.method ?? "";
  const methodsToProtect = csrfConfig.methodsToProtect ?? [];
  if (!methodsToProtect.includes(method)) {
    return;
  }

  const secret = getCookie(event, csrfConfig.cookieKey!) ?? "";
  const token = getHeader(event, baseConfig.headerName!) ?? "";

  const secretKey = await useSecretKey(csrfConfig);

  console.log(secret, token, secretKey); // <------ Log in the screenshot above.

  // verify the incoming csrf token
  const isValidToken = await csrf.verify(
    secret,
    token,
    secretKey,
    csrfConfig.encryptAlgorithm
  );
  if (!isValidToken) {
    throw createError({
      statusCode: 403,
      name: "EBADCSRFTOKEN",
      statusMessage: "CSRF Token Mismatch",
    });
  }
});
```

<img width="1021" alt="Screenshot 2024-08-20 at 17 29 42" src="https://github.com/user-attachments/assets/9d6081e5-d7a8-4dd1-81e2-1ab770672070">

<img width="982" alt="Screenshot 2024-08-20 at 17 30 19" src="https://github.com/user-attachments/assets/b4c6fa53-61e5-4b3a-8e87-ac2c8eb9e366">

@Morgbn is there a way to make it stable?

**Comment by Morgbn** [comment]
Hello @Barbapapazes, thanks for the detailed question!
I think I've figured out why after about ten seconds the token changes:
`useSecretKey` store `secretKey` in a global var, that not compatible with serverless functions...
I'll look for a solution to this problem

**Comment by atinux** [comment]
It may need some rewrite for the config, if the secretKey should be change after the build, I suggest to generate it in the module at build time and store it in the `runtimeConfig`

**Comment by bojanrajh** [comment]
@atinux Wouldn't that break cross-deploy form submissions? And is there something wrong with `encryptSecret` being statically defined?

**Comment by MineDrum** [comment]
I've just come across this issue while using nuxt-security with NuxtHub

Is there some sort of work around or a fix on the horizon?

**Comment by Barbapapazes** [comment]
Hey @Morgbn,

I've take a look at your changes but I have a little question.

While I can set `encryptSecret` within the module config, is there a way to setup it through the runtime config to use environment variable?
