### ISSUE TITLE
npm run build ‘production mode’ in SSR causes 403 CSRF Token Mismatch error.

### ISSUE THREAD

**Issue by myaaaapon** [Morgbn/nuxt-csurf#48]
This module has helped me a lot.
Thank you for everything 😊

```
nuxt@3.13.0
nuxt-security@2.0.0-rc.9
nuxt-csurf@1.6.1
```

If I run in `production` mode with `SSR`, I get a `403 CSRF Token Mismatch` error.

A 403 error will occur in the following cases.   [`node .output/server/index.mjs`](https://nuxt.com/docs/getting-started/deployment#entry-point)
```sh
# NODE_ENV=production

$ npm run build
$ npm run start（this means `node .output/server/index.mjs`）
```

However, If I run the following I do not get the 403 error
```sh
# NODE_ENV=development

$ npm run dev
```

# My Solution

`CookieKey` must always be set in `production`, even though it is optional.
That way I could avoid the 403 error.

```diff
# nuxt.config.ts

csurf: {
+    cookieKey: `csrf`,  // This is optional but always required in `NODE_ENV=production` mode.
},.
```

I have a feeling that the configuration `__Host-csrf` is only used for `https`, and `csrf` for everything else, which is causing the bug. 🤔
And I would like to get your opinion because sometimes I want to try the production mode which is not https in the local environment. 😊

**Comment by Morgbn** [comment]
Hello, if you want to test production on localhost you may add these two env variables:

```.env
NITRO_CSURF_HTTPS=false
NITRO_CSURF_COOKIE_KEY=csrf
```

I will add this to the doc.
For real production, https must be true and cookie key prefixed with `__Host`
