### ISSUE TITLE
No TS types respected of data

### ISSUE THREAD

**Issue by JoniLieh** [Morgbn/nuxt-csurf#49]
When using `useCsrfFetch`, you cant specify the return data type:

```ts
const {
  data, 
  error, 
  status,
} = await useCsrfFetch<Log[]>('/api/admin/logs');
```
![image](https://github.com/user-attachments/assets/5a52053b-1e51-42cf-a059-ed2ca1842de8)

**Expected:**
![image](https://github.com/user-attachments/assets/87dc100d-4e8a-46ea-bef5-2568340556ce)

**Comment by JoniLieh** [comment]
For the record: Building your own useFetch function and implementing the csrf token in the header is the best solution

**Comment by WuChenDi** [comment]
@Morgbn HI,

I apologize for the interruption.

I noticed that this issue has been marked as closed, yet it persists in the latest version I am using. Therefore, I would like to inquire whether it has not yet been addressed in the most recent release.
