### ISSUE TITLE
You also need to create a feature that can set csrf token before first csrf request

### ISSUE THREAD

**Issue by videmann** [Morgbn/nuxt-csurf#6]
And i have it. Will you contribute?

**Comment by Morgbn** [comment]
Can you elaborate on the use case?
If you have already implemented this feature, you can contribute by creating a pull request :)

**Comment by Morgbn** [comment]
For information, a csrf token is created on each request via a [server middleware](https://github.com/Morgbn/nuxt-csurf/blob/main/src/runtime/server/middleware/csrf.ts)
