### ISSUE TITLE
Does not work with SSR: false

### ISSUE THREAD

**Issue by McPizza0** [Morgbn/nuxt-csurf#8]
Applying `ssr: false` to nuxt.config breaks the CSRF composable.
The cookie is generated correctly, but the csrf token is not passed back to the client and therefore `useCsrf()` always returns `undefined`

**Comment by McPizza0** [comment]
After speaking with @Baroshem in the Nuxt Discord:  https://discord.com/channels/473401852243869706/1087072837648519298/1087072837648519298

I have decided to close this issue as it seems to not be feasible to implement CSRF without SSR in this manner
I'll look at alternative methods and If I find something universal to implement, I'll open a PR

**Comment by Morgbn** [comment]
Great, can't wait to see your implementation. PRs are welcome :)
