### ISSUE TITLE
csrf doesn't work in the SSR

### ISSUE THREAD

**Issue by alnow0021** [Morgbn/nuxt-csurf#9]
Hi,
when I visit the page for the first time (csrf cookie is not created yet) and try to fetch some data on the server side, then the module throws the error:

`FetchError:  (403 CSRF Token Mismatch (/api/data))`

After refresh the page, the data are fetched correctly on the server side

**example of code:**

```vue
<template>
  <div>
    <div>
      backend: {{ data }}
    </div>
    <div>
      error: {{ error }}
    </div>
  </div>
</template>

<script lang="ts" setup>
const {data, error} = useCsrfFetch('/api/data', {
  method: 'POST',
  body: {
    param: 1
  }
})
</script>
```

**nuxt.config.ts:**
```ts
export default defineNuxtConfig({
  modules: ['nuxt-security'],

  security: {
    csrf: true
  },
})
```

**Comment by Morgbn** [comment]
Hi, client-side rendering is not yet supported, I'm working on it for the next major release
